### ISSUE TITLE
Patch for /trunk/src/Library/Ude.Core/SBCSGroupProber.cs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Lexcess/Chartect.IO#8]
```
big problem!
not worked in line 103
```

Original issue reported on code.google.com by `Martinc...@gmail.com` on 15 Apr 2015 at 8:52

Attachments:
* [SBCSGroupProber.cs.patch](https://storage.googleapis.com/google-code-attachments/ude/issue-8/comment-0/SBCSGroupProber.cs.patch)

**Comment by Lexcess** [comment]
This has now been fixed in trunk. Thanks.
